### ISSUE TITLE
LDK Node v0.2 Tracking Issue

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#107]
- [x] Upgrade to LDK 0.0.116 (#105)
- [x] Upgrade to LDK 0.0.117 (#151)
- [x] Upgrade to LDK 0.0.118 (#175)
- [x] Remember and sweep spendable outputs (#94)
- [x] Figure out *if* we need to cache broadcasts, handle rebroadcasting (#22)
- [x] Figure out if/how we need to expose more (e.g., #90)
- [x] Add python packaging (#128)
- [x] Allow to check if node is running (#164)
- [x] Fix peer info persistence for inbound channels (#133)

**Comment by ariard** [comment]
We can add #98 as a v0.2 target ? Interested to collect more feedbacks from the LDK ecosystem at large.

**Comment by ariard** [comment]
> I don't think so as this issue is meant to be a (short-term) tracking issue for the 0.2 release, while https://github.com/lightningdevkit/ldk-node/issues/98 seems like a much longer term project, most of which probably will live outside this repository (namely, any binary/daemon).

Okay I'll see to build on top of ldk-node as this is already a huge simplification of our base API and move a binary/daemon in its own repository. If we spend time on communication cost over engineering time it's not worthy to share the maintenance cost.
