### ISSUE TITLE
LDK Node v0.4 Tracking Issue

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#167]
- [x] Update to LDK 0.0.124 / BDK 1.0 / rust-bitcoin 0.32 (#358)
    - [x] (Partially) revert BDK workaround (#359)
    - [x] Support incremental syncing (#362)
- [x] Additional `ChainDataSource` backend support
    - [x] Add `bitcoind` RPC support (#370)
- [x] Initial experimental VSS support (#246)
    - [x] Handle persistence failures gracefully, i.e., actually make use of fallible events, for example. (partly addressed in #374)
- [x] Allow to set `max_total_routing_fee_msat` (#166)
