### ISSUE TITLE
LDK Node v0.3 Tracking Issue

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#192]
- [x] Upgrade to LDK v0.0.122 (#243)
- [x] Drop `KVStore` bound from `Node` (#244)
- [x] Anchor support (#141)
- [x] BOLT 12 support (#193)
    - [x] Prefactor: Introduce `ConnectionManager` (#266) 
- [x] LSP Client integration (#194)
- [x] Expose unified balance interface (#250)
- [x] Find long-term solution for Swift issue (#231)
- [x] Async event handling (#224)
- [x] Add `last_update` timestamp (#57)
- [x] Expose fees paid (#255)
- [x] Expose `PaymentFailureReason` (#259)
- [x] Expose `ClosureReason` (#247)
- [x] Expose node status and statistics (#127)
- [x] Allow manual register/claim of payments (#280)
- [x] Expose `NetworkGraph` (#293)
- [x] Misc fixes (#281)
- [x] Archive old `ChannelMonitor`s (#300)
- [x] Set inflight limit to 100% for private channels (#303)
