### ISSUE TITLE
VSS Integration Tracking

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#246]
Most of the work is already merged, here we add some tracking for the remaining tasks:

- [x] Expose the capability to setup with `VssStore` in bindings (#376).
    - [x] Expose the capability to use a custom `AuthMethod` (#369).
    - [x] Expose the capability with a simpler default authentication method. (#369)
- [ ] Figure out how to handle the remaining 'panic-on-persistence-failure' cases, especially where we can't return an error, such as in the `EventHandler`. This might be a tough one.
    - [x] Short term we could consider just log the persistence failures when `VssStore` is configured, but it's probably safer to keep panicking. In any case we need to add some **huge** warning that VSS is considered experimental and that either data might be lost at any time or that LDK Node / the app using it might crash at any time if the connection is lost. (#369)
    - [x] Partially addressed panic-on-persistence failure in (#374)
    - [ ] Still need to address remaining cases (#381)
    - [ ] Still need #380
    - [x] Mid- to longer term we need to switch to a proper async-persistence `KVStore` interface and find better solutions in LDK, which in turn would allow us here to retry and then restart everything on persistence failure.
 - [x] Integrate a simple-to-use auth method. (#369)
     - [x] Possibly also expose a custom auth method via the `AuthMethod` trait, but this is already an *advanced* feature  as it requires user to understand the interface and write matching code instead of providing some credentials. (#369)
 - [x] Remove the `cfg`-gate. (#376)

(cc @G8XSU)

**Comment by tnull** [comment]
Closing this as remaining tasks have their own issues.
