### ISSUE TITLE
 LDK Node v0.5 Tracking Issue

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#360]
- [x] Add support for acting as LSPS1 client (#418)
- [x] Add Electrum support (#486)
- [x] Allow to override fee rate for on-chain operations (#176)
- [x] Expose on-chain payments in payment store (#432)
- [x] Allow honoring reserve in `send_all_to_address` (#345)
- [x] Allow to use custom loggers (#309)
- [x] Start verifying gossip (#377)
- [x] Allow to use description hash (#438)
- [x] Reject inbound requests for announced channels if we're not in 'forwarding mode' (#423)
- [x] Expose `short_channel_id` in `ChannelDetails` (https://github.com/lightningdevkit/ldk-node/issues/419)
