### ISSUE TITLE
LDK Node v0.1 Tracking Issue

### ISSUE THREAD

**Issue by tnull** [lightningdevkit/ldk-node#45]
In this issue we document progress on the remaining items for a 0.1 release:

- [x] Basic functionality in Rust (#11)
     - [x] Provide usage example and readme (#35)
     - [x] Extend test coverage by introducing `proptest`
     - [x] Add the capability of configuring a `seed: [u8; 32]`
- [x] Payment store (#13)
    - [x] ~~Add last change timestamp to `PaymentInfo`~~
    - [x] ~~Expose method to retrieve recent payments based on timestamp.~~
    - [x] Expose method to retrieve payments based on filter.
    - [x] ~~Create and impl `KVStoreUnpersister` trait~~
    - [x] Create and impl `KVStore` trait
- [x] Expose connect/disconnect methods (#52)
- [x] Add `ChannelPending` event (#60)
- [x] Allow spending on-chain funds (#61)
- [x] Impl ~~`KVStorePersister`~~ `KVStore`-based SQLite backend (#100)
- [x] Rethink serialization (#30)
     - [x] Re-use upstream serialization macros for now (#23)
     - [x] Figure out compat. guarantees
     - [x] Figure out format/framework to use
- [x] Regularly broadcast node announcements (#93)
- [x] Switch to use `NetAddress`es (#85)
- [x]  ~~Maybe:~~ Uniffi bindings (#25)
    - [x] Expose remaining interface methods (e.g., `list_peers`, `list_channels`) (#56)
    - [x] Review and merge in https://github.com/tnull/ldk-node/pull/1
    - [x] Test Kotlin packaging vs local maven
    - [x] Impl Kotlin publishing vs Maven Central (#59)
    - [x] Test Swift packaging (#114)
- [x] ~~Maybe:~~ Integrate RGS (#70)
- [x] 0conf channel support (#69)
- [x] Non-blocking event queue access (#91)
- [x] Include non-permanently connected peers in `list_peers()` (#95)
- [x] Only avoid duplicate payments if we didn't fail sending (#96)
- [x] Enforce successful initial fee rate update (#102)
- [x] Expose easy way to set log level (#108)
- [x] Move builder to dedicated module and improve its Rust API (#115)
- [x] Don't panic when avoidable (#119)
- [x] Allow to set `ChannelConfig` (#122)
- [x] Update some config defaults and expose them in bindings (#124)
- [x] Expose BIP39 generation (#113)
- [x] Remove superfluous `SendingFailed` status (#125)

## Release prep:
- [x] Switch default network config to `bitcoin` (#88)
- [x] Go once more over serialization #76 
- [x] Document and enforce MSRV #114 
- [x] Update version number in Rust and *all* bindings.
- [x] Upload Swift package and update checksum.

## Post release
- [ ] Update README to include instructions for bindings.
- [ ] Publish Python package (#128)
- [x] Publish Kotlin/JVM package
